apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appLabel }}
  ports:
  - name: hello-world-default-port
    port: {{ .Values.port }}
    targetPort: {{ .Values.applicationPort }}
